# for building
version: '3.9'

services:
  ldap-mailcow:
    container_name: ldap-mailcow
    #image: drlight17/ldap-mailcow:latest
    build:
      context: .
      dockerfile: Dockerfile
# uncomment to run container in detached mode
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#    depends_on:
#      - nginx-mailcow
    volumes:
      - ./data/ldap:/db:rw
      - ./data/conf/dovecot:/conf/dovecot:rw
      - ./data/conf/sogo:/conf/sogo:rw
# uncomment for develop
#      - type: bind
#        source: ./syncer.py
#        target: /syncer.py
#      - type: bind
#        source: ./api.py
#        target: /api.py
#      - type: bind
#        source: ./filedb.py
#        target: /filedb.py
    environment:
      - LDAP-MAILCOW_LDAP_URI=ldap://
      - LDAP-MAILCOW_LDAP_BASE_DN=
      - LDAP-MAILCOW_LDAP_BIND_DN=
      - LDAP-MAILCOW_LDAP_BIND_DN_PASSWORD=password
      - LDAP-MAILCOW_API_HOST=
      - LDAP-MAILCOW_API_KEY=
      - LDAP-MAILCOW_SYNC_INTERVAL=3600
      # set LDAP-MAILCOW_LDAP_AVA_ATTR and LDAP-MAILCOW_LDAP_QUOTA_ATTR to any random string value if you don't want to asu these attributes
      - LDAP-MAILCOW_LDAP_AVA_ATTR=jpegPhoto
      - LDAP-MAILCOW_LDAP_QUOTA_ATTR=st
      - LDAP-MAILCOW_LDAP_FILTER=(&(mail=*)(objectClass=user))
      - LDAP-MAILCOW_SOGO_LDAP_FILTER=((objectClass='user') AND (mail='*@domain.org'))
#    restart: always
    network_mode: host

